name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    uses: nwilson5/cicd/.github/workflows/validate.yml@main
    with:
      working-directory: .
      python-version: "3.14"
